services:
  dbUser:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  dbAdmin:
    image: postgres:9.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5433:5432"
  dbLogin:
    image: mysql:8.0.36-debian
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: google_oauth2_login
    ports:
      - "3306:3306"
