services:
  dbUser:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  dbAdmin:
    image: postgres:9.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5433:5432"
  dbLogin:
    image: postgres:9.6
    environment:
      POSTGRES_USER: proxy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5434:5432"
  dbPresenca:
    image: mongo:7.0.8
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=presenca
    command: mongod --auth
    volumes:
      - ./presenca-api/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
